from typing import Dict, List, Optional
import pandas as pd
import os
import json

def fix_encoding_text(text: Optional[str]) -> str:
    """
    Fixes encoding of a string using ISO-8859-1 (Latin-1) encoding
    :param text -- string to fix
    :return -- string with fixed encoding
    """
    if not text:
        return ""

    try:
        return text.encode('latin-1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

def load_message_data(path_to_data: str) -> pd.DataFrame:
    """
    Loads messages from JSON files generated by Facebook export tool
    :param path_to_data -- path to folder with JSON files
    :return -- DataFrame containing messages with corresponding dates and senders
    """
    if not os.path.exists(path_to_data):
        raise FileNotFoundError(f"Path {path_to_data} does not exist")

    dfs = []

    for file in os.listdir(path_to_data):
        if file.endswith(".json"):
            with open(os.path.join(path_to_data, file), "r", encoding="utf-8") as f:
                data = json.load(f)
                messages_raw = data.get("messages", [])

                if messages_raw:
                    dfs.append(process_message_data(messages_raw))

    if not dfs:
        return pd.DataFrame(columns=["send_datetime", "message", "sender_name"])

    return pd.concat(dfs, ignore_index=True)


def process_message_data(data: List[Dict]) -> pd.DataFrame:
    """
    Converts processed message data to a DataFrame
    :param data -- list of dicts containing message data
    :return -- DataFrame
    """
    df = pd.DataFrame(data)

    if 'content' in df.columns:
        df['message'] = df['content'].apply(fix_encoding_text)
    else:
        df['message'] = ""

    df['send_datetime'] = pd.to_datetime(df['timestamp_ms'], unit='ms')

    available_cols = [c for c in ['send_datetime', 'message', 'sender_name'] if c in df.columns]
    return df[available_cols]